# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-01-16 02:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rbac', '0004_auto_20190108_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('contact', models.CharField(max_length=32)),
                ('company_address', models.CharField(max_length=128)),
                ('receive_address', models.CharField(max_length=128)),
                ('receiver', models.CharField(max_length=32)),
                ('contact_phone', models.CharField(max_length=128)),
                ('receiver_phone', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('jianjie', models.CharField(max_length=200)),
                ('bid', models.DecimalField(decimal_places=2, max_digits=8)),
                ('bid_num', models.IntegerField()),
                ('bin_money', models.DecimalField(decimal_places=2, max_digits=8)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('sale_num', models.IntegerField()),
                ('sale_money', models.DecimalField(decimal_places=2, max_digits=8)),
                ('kuncui', models.IntegerField()),
                ('unit', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.CharField(max_length=32)),
                ('order_date', models.DateTimeField()),
                ('order_state', models.CharField(max_length=128)),
                ('order_money', models.DecimalField(decimal_places=2, max_digits=9)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Company')),
                ('goods', models.ManyToManyField(to='goods.Goods')),
                ('userinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbac.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='TypeGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='goods',
            name='typegoods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.TypeGoods'),
        ),
    ]
