# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-01-16 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='actual_paymen',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='实付款'),
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_data',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_expense',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='运费'),
        ),
        migrations.AddField(
            model_name='goods',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='利润'),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='actual_paymen',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='实付款'),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='order_expense',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='运费'),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='order_orther',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='其他支出'),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='利润'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='bid',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='进价'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='bid_num',
            field=models.IntegerField(verbose_name='进货数量'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='bin_money',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='进货总价'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='sale_money',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='销售总价'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='sale_num',
            field=models.IntegerField(verbose_name='销售数量'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='售价'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='unit',
            field=models.CharField(max_length=20, verbose_name='单位'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='order_money',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='订单金额'),
        ),
    ]
