# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-01-16 06:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20190116_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='bin_money',
            new_name='bid_money',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='bid',
        ),
        migrations.AddField(
            model_name='goods',
            name='bid_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='进价'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_data',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='jianjie',
            field=models.CharField(max_length=300),
        ),
    ]
