# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-01-04 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='entry_time',
            field=models.DateTimeField(default='2018-08-08'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='gender',
            field=models.IntegerField(choices=[(1, '男'), (2, '女')], default=1),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='state',
            field=models.IntegerField(choices=[(1, '试用期'), (2, '在职'), (3, '离职')], default=2),
        ),
    ]
