# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-01-08 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_auto_20190108_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='card_id',
            field=models.CharField(max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='phone',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
